global_costmap:
  global_frame: /map # coordinate frame the costmap should run in
  robot_base_frame: base_link # coordinate frame the costmap should reference for the base of the robot.
  update_frequency: 5.0
  publish_frequency: 0.5
  #resolution: 0.005
  #width: 5
  #height: 5
  static_map: true # Determines whether or not the costmap should initialize itself based on a map served by the map_server.
  #inflation_radius: 2.5
  transform_tolerance: 0.5
  #origin_x: 0.0
  #origin_y: 0.0
  #rolling_window: true
