#local_costmap:
  #global_frame: odom # /map #odom
  #robot_base_frame: base_link
  #update_frequency: 5.0
  #publish_frequency: 2.0
  #transform_tolerance: 0.5
  #static_map: true #false
  #rolling_window: fasle #true
  #width: 0.5
  #height: 0.5
  #resolution: 0.005

################################################################################
  #origin_x: 0.25
  #origin_y: 0.25
  #plugins:
  #  - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
  #  - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
#local_costmap:
  #global_frame: odom #/map
  #robot_base_frame: base_link
  #update_frequency: 5.0
  #publish_frequency: 5.0
  #transform_tolerance: 0.5
  #rolling_window: false
  ##static_map: true #false
